"""add uuid column

Revision ID: 1b0d2c4685b3
Revises: 4a6d2759e70f
Create Date: 2022-10-26 17:41:07.137915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0d2c4685b3'
down_revision = '4a6d2759e70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eli_voter', sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eli_voter', 'uuid')
    # ### end Alembic commands ###
