"""empty message

Revision ID: 3902c9aa0974
Revises: ba559daa5e94
Create Date: 2022-10-25 11:28:46.404188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3902c9aa0974'
down_revision = 'ba559daa5e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eli_voter', 'uuid',
               existing_type=sa.BLOB(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eli_voter', 'uuid',
               existing_type=sa.BLOB(),
               nullable=True)
    # ### end Alembic commands ###
