"""add uuid column

Revision ID: 4743d90beeb0
Revises: 57bc2fd038ae
Create Date: 2022-10-26 16:36:11.024306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4743d90beeb0'
down_revision = '57bc2fd038ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eli_voter', sa.Column('uuid', postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eli_voter', 'uuid')
    # ### end Alembic commands ###
