"""add uuid column

Revision ID: 4a6d2759e70f
Revises: 4743d90beeb0
Create Date: 2022-10-26 16:40:06.926737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a6d2759e70f'
down_revision = '4743d90beeb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eli_voter', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eli_voter', 'uuid')
    # ### end Alembic commands ###
