"""empty message

Revision ID: 57bc2fd038ae
Revises: d5f3413a1365
Create Date: 2022-10-26 15:53:59.329203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57bc2fd038ae'
down_revision = 'd5f3413a1365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eli_voter', sa.Column('adminplk', sa.BLOB(), nullable=True))
    op.add_column('eli_voter', sa.Column('voterpvk', sa.BLOB(), nullable=True))
    op.add_column('eli_voter', sa.Column('uuid', postgresql.UUID(), nullable=True))
    op.drop_column('eli_voter', 'pubkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eli_voter', sa.Column('pubkey', sa.INTEGER(), nullable=True))
    op.drop_column('eli_voter', 'uuid')
    op.drop_column('eli_voter', 'voterpvk')
    op.drop_column('eli_voter', 'adminplk')
    # ### end Alembic commands ###
