"""empty message

Revision ID: ba559daa5e94
Revises: 461d75d910bf
Create Date: 2022-10-25 11:24:01.381474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba559daa5e94'
down_revision = '461d75d910bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eli_voter', sa.Column('uuid', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eli_voter', 'uuid')
    # ### end Alembic commands ###
