"""empty message

Revision ID: d5f3413a1365
Revises: 3902c9aa0974
Create Date: 2022-10-25 23:05:49.241598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f3413a1365'
down_revision = '3902c9aa0974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eli_voter', sa.Column('adminplk', sa.Integer(), nullable=True))
    op.add_column('eli_voter', sa.Column('voterpvk', sa.Integer(), nullable=True))
    op.drop_column('eli_voter', 'pubkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eli_voter', sa.Column('pubkey', sa.INTEGER(), nullable=True))
    op.drop_column('eli_voter', 'voterpvk')
    op.drop_column('eli_voter', 'adminplk')
    # ### end Alembic commands ###
